<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="family" name="com.test.PresentationPageTest" tests="4" failures="0" timestamp="22 Sep 2016 06:26:43 GMT" time="37.748" errors="1">
  <testcase name="testPresentationPage" time="5.980" classname="com.test.PresentationPageTest"/>
  <testcase name="testPresentationPage" time="6.561" classname="com.test.PresentationPageTest"/>
  <testcase name="testPresentationPage" time="19.255" classname="com.test.PresentationPageTest">
    <error type="org.testng.TestNGException" message="
The data provider is trying to pass 1 parameters but the method com.test.PresentationPageTest#testPresentationPage takes 3 and TestNG is unable in inject a suitable object">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 1 parameters but the method com.test.PresentationPageTest#testPresentationPage takes 3 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1255)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1251)
	... 17 more
]]>
    </error>
  </testcase> <!-- testPresentationPage -->
  <testcase name="testPresentationPage" time="5.952" classname="com.test.PresentationPageTest"/>
</testsuite> <!-- com.test.PresentationPageTest -->
